# site settings
title: Cybersecurity
subtitle: Information Technology
email: jrluisfernandez@gmail.com
description: I am interactive. It's my intent to find solutions, and my perserverance comes from connecting consumers with todays technology. Technology Systems are complex and require understanding. Today's consumers are more connected than ever before, that's why I support, and secure their experience. 
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Forest Ridge
city: Winter Haven
state: FL
zip_code: 33881
country: United States of America
phone: (863) 236-9235

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: https://avatars0.githubusercontent.com/u/40038841?s=460&v=4
facebook_url: https://www.facebook.com/reggaeton1991
github_url: https://github.com/LuisFernandezJr
instagram_url: 
linkedin_url: https://www.linkedin.com/in/luisfernandezjr/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
